//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListSLG.resources.text {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class adviseTextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal adviseTextResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListSLG.resources.text.adviseTextResource", typeof(adviseTextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}が生まれました。戦闘に参加できるのは2期後になります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string birth {
            get {
                return ResourceManager.GetString("birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が成長し、戦闘に出れるようになりました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string growth {
            get {
                return ResourceManager.GetString("growth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}が引退しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string retire {
            get {
                return ResourceManager.GetString("retire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   期末です。余った威信は次期に繰り越せませんので、技術の採用や配偶を行いましょう。
        ///威信が不足している場合は将軍を解任してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string term {
            get {
                return ResourceManager.GetString("term", resourceCulture);
            }
        }
    }
}
