//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListSLG.resources.text {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class techInfoTextResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal techInfoTextResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ListSLG.resources.text.techInfoTextResource", typeof(techInfoTextResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   配偶コマンドを有効化します。新たな将軍を作成できます。
        ///将軍一覧の右クリックメニューから可能です。
        ///※ゲーム開始時点で採用済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   各家ごとに5人まで将軍の維持費が発生しなくなります。
        ///（通常は3人まで） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   敗北時の威信増加量がアップします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   歩兵の編制を有効化し、軍団の編制数が3増えます。
        ///防御力が高く、中央への攻撃を防ぎます。
        ///※ゲーム開始時点で採用済み に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   騎兵の編制を有効化し、軍団の編制数が2増えます。
        ///騎兵は防御力が低いですが、攻撃力が高いです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投射兵の編制を有効化し、軍団の編制数が2増えます。
        ///投射兵は秀でた能力はありませんが、安定したダメージを与えます。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   昇格コマンドを有効化します。
        ///昇格毎に兵数が500増えますが、維持費も増えます。
        ///将軍一覧の右クリックメニューから可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分家コマンドを有効化します。その将軍の一族で新たな軍団を作成します。
        ///将軍一覧の右クリックメニューから可能です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自軍の将軍同士の配偶を可能にします。
        ///威信コストはかかりませんが、成長力はの増加は期待できません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   歩兵の防御力を強化します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   騎兵の機動力を強化し、敵の防御を回避しやすくなります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   投射兵の攻撃力を強化します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
    }
}
